import { b } from "./shared";

/** Additional consumer / fintech / creator tools for broader real-world coverage. */
export const EXTRA_CONSUMER_BRANDS = [
  b("wise.com", ["wise", "transferwise"]),
  b("revolut.com", ["revolut"]),
  b("chime.com", ["chime"]),
  b("cash.app", ["cash app", "cashapp"]),
  b("venmo.com", ["venmo"]),
  b("paypal.com", ["paypal"]),
  b("klarna.com", ["klarna"]),
  b("affirm.com", ["affirm"]),
  b("afterpay.com", ["afterpay"]),
  b("zip.co", ["zip pay", "quadpay"]),
  b("intuit.com", ["quickbooks", "turbotax", "mint.com", "mint intuit"]),
  b("creditkarma.com", ["credit karma", "creditkarma"]),
  b("nerdwallet.com", ["nerdwallet", "nerd wallet"]),
  b("robinhood.com", ["robinhood", "robin hood"]),
  b("fidelity.com", ["fidelity investments", "fidelity"]),
  b("schwab.com", ["charles schwab", "schwab"]),
  b("vanguard.com", ["vanguard"]),
  b("acorns.com", ["acorns invest", "acorns"]),
  b("stash.com", ["stash invest", "stash"]),
  b("rakuten.com", ["rakuten", "ebates"]),
  b("capitalone.com", ["capital one", "capitalone"]),
  b("chase.com", ["chase sapphire", "jpmorgan chase", "chase"]),
  b("americanexpress.com", ["american express", "amex"]),
  b("discover.com", ["discover card", "discover"]),
  b("citi.com", ["citi card", "citibank", "citi.com"]),
  b("bankofamerica.com", ["bank of america", "bofa"]),
  b("wellsfargo.com", ["wells fargo", "wellsfargo"]),
  b("usaa.com", ["usaa"]),
  b("navyfederal.org", ["navy federal"]),
  b("allstate.com", ["allstate"]),
  b("progressive.com", ["progressive insurance", "progressive"]),
  b("geico.com", ["geico"]),
  b("statefarm.com", ["state farm"]),
  b("lemonade.com", ["lemonade insurance", "lemonade"]),
  b("perplexity.ai", ["perplexity ai", "perplexity"]),
  b("cursor.com", ["cursor ide", "cursor"]),
  b("replit.com", ["replit"]),
  b("midjourney.com", ["mid journey", "midjourney"]),
  b("runwayml.com", ["runway ml", "runway"]),
  b("elevenlabs.io", ["elevenlabs", "eleven labs"]),
  b("weightwatchers.com", ["weight watchers", "ww.com", "ww membership"]),
  b("noom.com", ["noom"]),
  b("asos.com", ["asos"]),
  b("uniqlo.com", ["uniqlo"]),
  b("hm.com", ["h&m", "h and m", "hm.com"]),
  b("zara.com", ["zara"]),
  b("backcountry.com", ["backcountry"]),
  b("patagonia.com", ["patagonia"]),
  b("allbirds.com", ["allbirds"]),
  b("warbyparker.com", ["warby parker", "warbyparker"]),
  b("dollarshaveclub.com", ["dollar shave club", "dollar shave"]),
  b("birchbox.com", ["birchbox"]),
  b("ipsy.com", ["ipsy"]),
  b("fabfitfun.com", ["fabfitfun"]),
  b("bookofthemonth.com", ["book of the month", "botm"]),
];
