import { b } from "./shared";

export const FITNESS_GAMING_BRANDS = [
  b("onepeloton.com", ["peloton", "onepeloton"]),
  b("planetfitness.com", ["planet fitness", "planetfitness"]),
  b("crunch.com", ["crunch fitness", "crunch gym", "crunch"]),
  b("equinox.com", ["equinox", "equinox+"]),
  b("orangetheory.com", ["orangetheory", "orange theory"]),
  b("barrysbootcamp.com", ["barrys bootcamp", "barry's bootcamp"]),
  b("lafitness.com", ["la fitness"]),
  b("24hourfitness.com", ["24 hour fitness", "24hourfitness"]),
  b("anytimefitness.com", ["anytime fitness"]),
  b("lifetime.life", ["life time athletic", "life time", "lifetime fitness"]),
  b("ymca.org", ["ymca"]),
  b("strava.com", ["strava", "strava subscription"]),
  b("whoop.com", ["whoop"]),
  b("myfitnesspal.com", ["my fitness pal", "myfitnesspal"]),
  b("nike.com", ["nike training club", "ntc"]),
  b("ifit.com", ["ifit", "nordictrack"]),
  b("nintendo.com", ["nintendo switch online", "nintendo"]),
  b("playstation.com", ["playstation plus", "playstation now", "ps plus", "psn", "playstation"]),
  b("xbox.com", ["xbox game pass", "xbox live gold", "xbox"]),
  b("steampowered.com", ["steam deck", "steam"]),
  b("ea.com", ["ea play", "electronic arts"]),
  b("epicgames.com", ["epic games", "fortnite crew"]),
  b("roblox.com", ["roblox premium", "roblox"]),
  b("twitch.tv", ["twitch turbo", "twitch"]),
  b("discord.com", ["discord nitro", "discord"]),
  b("curseforge.com", ["curseforge"]),
  b("humblebundle.com", ["humble choice", "humble bundle"]),
];
