import { b } from "./shared";

export const FOOD_GROCERY_BRANDS = [
  b("starbucks.com", [
    "starbucks store",
    "starbucks coffee",
    "starbucks",
  ], { padding: "tight" }),
  b("mcdonalds.com", ["mcdonalds", "mcdonald", "mcd ", "golden arches"]),
  b("chipotle.com", ["chipotle mexican", "chipotle"]),
  b("subway.com", ["subway restaurant", "subway"]),
  b("wendys.com", ["wendys", "wendy's"]),
  b("burgerking.com", ["burger king", "bk ", "burgerking"]),
  b("tacobell.com", ["taco bell", "tacobell"]),
  b("kfc.com", ["kentucky fried", "kfc"]),
  b("dominos.com", ["dominos", "domino's pizza", "domino pizza"]),
  b("pizzahut.com", ["pizza hut", "pizzahut"]),
  b("papajohns.com", ["papa johns", "papa john's"]),
  b("dunkindonuts.com", ["dunkin donuts", "dunkin ", "dunkin"]),
  b("panerabread.com", ["panera bread", "panera"]),
  b("doordash.com", ["doordash", "door dash", "dashpass", "dash pass"]),
  b("ubereats.com", ["uber eats", "ubereats", "uber eats pass"]),
  b("grubhub.com", ["grubhub", "grub hub", "seamless"]),
  b("instacart.com", ["instacart", "insta cart", "instacart+"]),
  b("caviar.com", ["caviar delivery", "caviar"]),
  b("postmates.com", ["postmates"]),
  b("hellofresh.com", ["hello fresh", "hellofresh"]),
  b("blueapron.com", ["blue apron", "blueapron"]),
  b("factor75.com", ["factor 75", "factor75", "factor meals"]),
  b("freshly.com", ["freshly"]),
  b("gopuff.com", ["go puff", "gopuff"]),
  b("shipt.com", ["shipt", "target shipt"]),
  b("costco.com", ["costco wholesale", "costco membership", "costco"]),
  b("samsclub.com", ["sams club", "sam's club", "samsclub"]),
  b("kroger.com", ["kroger", "kroger plus"]),
  b("safeway.com", ["safeway"]),
  b("wholefoodsmarket.com", ["whole foods", "wholefoods"]),
  b("traderjoes.com", ["trader joes", "trader joe's"]),
  b("wegmans.com", ["wegmans"]),
  b("publix.com", ["publix"]),
  b("albertsons.com", ["albertsons"]),
  b("heb.com", ["h-e-b", "heb grocery"]),
  b("aldi.us", ["aldi"]),
  b("lidl.com", ["lidl"]),
  b("shakeshack.com", ["shake shack"]),
];
