import { b } from "./shared";

export const NEWS_TELCO_UTILITIES_BRANDS = [
  b("nytimes.com", ["new york times", "nytimes", "nyt.com"]),
  b("washingtonpost.com", ["washington post", "wp digital"]),
  b("wsj.com", ["wall street journal", "wsj"]),
  b("bloomberg.com", ["bloomberg", "bloomberg terminal"]),
  b("economist.com", ["the economist", "economist"]),
  b("theatlantic.com", ["the atlantic", "atlantic"]),
  b("medium.com", ["medium membership", "medium member", "medium"]),
  b("patreon.com", ["patreon"]),
  b("reddit.com", ["reddit premium", "reddit gold"]),
  b("linkedin.com", ["linkedin premium", "linkedin sales", "linkedin learning", "linkedin"]),
  b("verizon.com", ["verizon wireless", "verizon fios", "verizon"]),
  b("att.com", ["at&t", "att wireless", "att.com"]),
  b("t-mobile.com", ["t-mobile", "t mobile", "tmobile", "magenta"]),
  b("sprint.com", ["sprint"]),
  b("cricketwireless.com", ["cricket wireless", "cricket"]),
  b("visible.com", ["visible"]),
  b("mintmobile.com", ["mint mobile", "mintmobile"]),
  b("uscellular.com", ["us cellular"]),
  b("xfinity.com", ["xfinity", "comcast"]),
  b("spectrum.com", ["spectrum", "charter communications"]),
  b("cox.com", ["cox communications", "cox cable"]),
  b("optimum.com", ["optimum", "altice"]),
  b("duolingo.com", ["duolingo max", "duolingo plus", "duolingo"]),
  b("masterclass.com", ["masterclass"]),
  b("skillshare.com", ["skillshare"]),
  b("coursera.org", ["coursera plus", "coursera"]),
  b("udemy.com", ["udemy"]),
  b("pluralsight.com", ["pluralsight"]),
  b("codecademy.com", ["codecademy"]),
  b("brilliant.org", ["brilliant.org", "brilliant"]),
  b("headspace.com", ["headspace"]),
  b("calm.com", ["calm.com", "calm app"]),
  b("babbel.com", ["babbel"]),
  b("blinkist.com", ["blinkist"]),
];
