import { b } from "./shared";

export const RETAIL_SHOPPING_BRANDS = [
  b("amazon.com", [
    "amazon.com",
    "amazon marketplace",
    "amazon retail",
    "kindle unlimited",
    "amazon kindle",
    "amazon ",
  ]),
  b("walmart.com", ["walmart+", "walmart plus", "walmart.com", "walmart "]),
  b("target.com", ["target circle", "target redcard", "target.com", "target "]),
  b("costco.com", ["costco.com", "costco online"]),
  b("bestbuy.com", ["best buy total", "best buy", "bestbuy"]),
  b("homedepot.com", ["home depot", "homedepot"]),
  b("lowes.com", ["lowes", "lowe's"]),
  b("ikea.com", ["ikea family", "ikea"]),
  b("wayfair.com", ["wayfair"]),
  b("ebay.com", ["ebay"]),
  b("etsy.com", ["etsy plus", "etsy"]),
  b("mercari.com", ["mercari"]),
  b("poshmark.com", ["poshmark", "posh mark"]),
  b("depop.com", ["depop"]),
  b("shein.com", ["shein"]),
  b("temu.com", ["temu"]),
  b("nike.com", ["nike membership", "nike.com", "nike "]),
  b("adidas.com", ["adidas", "adidas.com"]),
  b("lululemon.com", ["lululemon", "lulu lemon"]),
  b("gap.com", ["gap inc", "gap.com", "banana republic", "old navy", "athleta"]),
  b("macys.com", ["macys", "macy's"]),
  b("nordstrom.com", ["nordstrom", "nordstrom rack"]),
  b("sephora.com", ["sephora"]),
  b("ulta.com", ["ulta beauty", "ulta"]),
  b("cvs.com", ["cvs carepass", "cvs pharmacy", "cvs"]),
  b("walgreens.com", ["walgreens", "mywalgreens"]),
  b("rei.com", ["rei co-op", "rei membership", "rei"]),
  b("zappos.com", ["zappos"]),
  b("chewy.com", ["chewy", "chewy.com"]),
  b("petsmart.com", ["petsmart", "pet smart"]),
  b("petco.com", ["petco", "vital care"]),
  b("gamestop.com", ["gamestop", "game stop"]),
  b("newegg.com", ["newegg"]),
  b("bhphotovideo.com", ["b&h photo", "bh photo"]),
];
