import { b } from "./shared";

/** Productivity, dev tools, cloud, security, AI, hosting. */
export const SOFTWARE_SAAS_BRANDS = [
  b("microsoft.com", [
    "microsoft 365",
    "office 365",
    "microsoft office",
    "xbox game pass ultimate",
    "xbox game pass",
    "xbox live",
    "microsoft copilot",
    "onedrive",
    "skype",
    "microsoft",
  ]),
  b("xbox.com", ["xbox", "xbox.com"]),
  b("adobe.com", [
    "adobe creative cloud",
    "creative cloud",
    "photoshop",
    "lightroom",
    "acrobat pro",
    "adobe stock",
    "adobe",
  ]),
  b("google.com", [
    "google workspace",
    "google one",
    "google storage",
    "google fi",
    "google play",
    "youtube studio",
    "google",
  ]),
  b("apple.com", [
    "icloud+",
    "icloud +",
    "icloud",
    "apple one",
    "apple arcade",
    "apple news",
    "apple fitness",
    "apple developer",
    "apple care",
    "apple.com",
    "apple bill",
  ], { padding: "snug" }),
  b("openai.com", [
    "chatgpt plus",
    "chatgpt team",
    "chatgpt business",
    "chatgpt",
    "openai api",
    "openai",
  ]),
  b("anthropic.com", [
    "claude pro",
    "claude max",
    "claude.ai",
    "claude subscription",
    "anthropic",
    "claude",
  ]),
  b("github.com", ["github copilot", "github team", "github pro", "github"]),
  b("gitlab.com", ["gitlab"]),
  b("bitbucket.org", ["bitbucket"]),
  b("jetbrains.com", ["jetbrains", "intellij", "pycharm", "webstorm"]),
  b("notion.so", ["notion ai", "notion"]),
  b("slack.com", ["slack"]),
  b("zoom.us", ["zoom pro", "zoom one", "zoom.us", "zoom"]),
  b("figma.com", ["figma professional", "figma"]),
  b("canva.com", ["canva pro", "canva"]),
  b("dropbox.com", ["dropbox plus", "dropbox business", "dropbox"]),
  b("box.com", ["box.com", "box inc"]),
  b("asana.com", ["asana"]),
  b("monday.com", ["monday.com", "monday com", "monday"]),
  b("airtable.com", ["airtable"]),
  b("trello.com", ["trello"]),
  b("atlassian.com", ["atlassian", "jira", "confluence", "trello"]),
  b("linear.app", ["linear"]),
  b("clickup.com", ["clickup"]),
  b("evernote.com", ["evernote"]),
  b("todoist.com", ["todoist"]),
  b("ticktick.com", ["ticktick"]),
  b("obsidian.md", ["obsidian sync", "obsidian"]),
  b("grammarly.com", ["grammarly"]),
  b("1password.com", ["1password"]),
  b("lastpass.com", ["lastpass"]),
  b("dashlane.com", ["dashlane"]),
  b("bitwarden.com", ["bitwarden"]),
  b("nordvpn.com", ["nordvpn", "nord vpn"]),
  b("expressvpn.com", ["expressvpn"]),
  b("surfshark.com", ["surfshark"]),
  b("proton.me", ["proton mail", "protonvpn", "proton pass", "proton drive", "proton"]),
  b("mozilla.org", ["mozilla vpn", "firefox relay"]),
  b("zapier.com", ["zapier"]),
  b("ifttt.com", ["ifttt"]),
  b("hubspot.com", ["hubspot"]),
  b("salesforce.com", ["salesforce"]),
  b("zendesk.com", ["zendesk"]),
  b("intercom.com", ["intercom"]),
  b("twilio.com", ["twilio"]),
  b("sendgrid.com", ["sendgrid"]),
  b("mailchimp.com", ["mailchimp", "intuit mailchimp"]),
  b("convertkit.com", ["convertkit"]),
  b("beehiiv.com", ["beehiiv"]),
  b("substack.com", ["substack"]),
  b("squarespace.com", ["squarespace"]),
  b("wix.com", ["wix premium", "wix"]),
  b("webflow.com", ["webflow"]),
  b("wordpress.com", ["wordpress.com", "wordpress"]),
  b("godaddy.com", ["godaddy"]),
  b("namecheap.com", ["namecheap"]),
  b("cloudflare.com", ["cloudflare"]),
  b("vercel.com", ["vercel"]),
  b("netlify.com", ["netlify"]),
  b("digitalocean.com", ["digitalocean", "digital ocean"]),
  b("linode.com", ["linode", "akamai cloud"]),
  b("render.com", ["render.com", "render deploy"]),
  b("fly.io", ["fly.io", "fly io"]),
  b("heroku.com", ["heroku"]),
  b("mongodb.com", ["mongodb atlas", "mongodb"]),
  b("supabase.com", ["supabase"]),
  b("planetscale.com", ["planetscale"]),
  b("neon.tech", ["neon.tech", "neon database"]),
  b("docker.com", ["docker hub", "docker"]),
  b("sentry.io", ["sentry"]),
  b("datadoghq.com", ["datadog"]),
  b("newrelic.com", ["new relic", "newrelic"]),
  b("pagerduty.com", ["pagerduty"]),
  b("launchdarkly.com", ["launchdarkly"]),
  b("mixpanel.com", ["mixpanel"]),
  b("amplitude.com", ["amplitude"]),
  b("segment.com", ["segment"]),
  b("stripe.com", ["stripe"]),
  b("paddle.com", ["paddle"]),
  b("miro.com", ["miro"]),
  b("loom.com", ["loom"]),
  b("whimsical.com", ["whimsical"]),
  b("excalidraw.com", ["excalidraw"]),
  b("calendly.com", ["calendly"]),
  b("cal.com", ["cal.com", "cal com"]),
  b("docusign.com", ["docusign"]),
  b("hellosign.com", ["dropbox sign", "hellosign"]),
  b("pandadoc.com", ["pandadoc"]),
  b("typeform.com", ["typeform"]),
  b("surveymonkey.com", ["survey monkey", "surveymonkey"]),
];
