import { b } from "./shared";

/** Streaming, music, podcasts, live TV bundles. */
export const STREAMING_BRANDS = [
  b("netflix.com", [
    "netflix.com",
    "netflix inc",
    "netflix streaming",
    "netflix",
  ]),
  b("hulu.com", ["hulu.com", "hulu llc", "hulu"]),
  b("disneyplus.com", [
    "disney+",
    "disney plus",
    "disneyplus",
    "disney streaming",
  ]),
  b("max.com", [
    "hbo max",
    "hbomax",
    "max streaming",
    "warnermedia",
    "max.com",
  ], { padding: "tight" }),
  b("peacocktv.com", ["peacock tv", "peacocktv", "peacock"]),
  b("paramountplus.com", ["paramount+", "paramount plus", "paramountplus", "paramount streaming"]),
  b("primevideo.com", ["prime video", "amazon prime video", "primevideo"]),
  b("audible.com", ["audible plus", "audible.com", "audible"]),
  b("amazon.com", [
    "amazon prime",
    "amazon channels",
    "amazon video",
    "amzn prime",
    "prime membership",
  ]),
  b("youtube.com", [
    "youtube premium",
    "youtube tv",
    "youtube music",
    "yt premium",
    "youtube red",
    "youtube",
  ]),
  b("spotify.com", ["spotify usa", "spotify.com", "spotify"]),
  b("music.apple.com", ["apple music", "itunes match", "itunes"], { padding: "snug" }),
  b("tidal.com", ["tidal hifi", "tidal"]),
  b("pandora.com", ["pandora one", "pandora plus", "pandora premium", "pandora"]),
  b("siriusxm.com", ["sirius xm", "siriusxm", "sirius"]),
  b("soundcloud.com", ["soundcloud go", "soundcloud"]),
  b("crunchyroll.com", ["crunchyroll", "funimation", "vrv"]),
  b("discoveryplus.com", ["discovery+", "discovery plus", "discoveryplus"]),
  b("showtime.com", ["showtime anytime", "showtime"]),
  b("starz.com", ["starzplay", "starz"]),
  b("fubo.tv", ["fubo tv", "fubotv", "fubo"]),
  b("sling.com", ["sling tv", "slingtv", "sling"]),
  b("philo.com", ["philo tv", "philo"]),
  b("britbox.com", ["britbox"]),
  b("acorn.tv", ["acorn tv", "acorn"]),
  b("shudder.com", ["shudder"]),
  b("criterionchannel.com", ["criterion channel", "criterion"]),
  b("mubi.com", ["mubi"]),
  b("dazn.com", ["dazn"]),
  b("espn.com", ["espn+", "espn plus", "espn watch"]),
  b("nba.com", ["nba league pass", "nba tv"]),
  b("mlb.com", ["mlb.tv", "mlb tv"]),
  b("nfl.com", ["nfl game pass", "nfl+"]),
  b("pluto.tv", ["pluto tv", "pluto"]),
  b("tubi.tv", ["tubi"]),
  b("roku.com", ["roku channel", "the roku channel", "roku"]),
  b("plex.tv", ["plex pass", "plex"]),
  b("vudu.com", ["vudu", "fandango at home"]),
  b("amcplus.com", ["amc+", "amc plus", "amc premiere"]),
  b("livetv.apple.com", ["apple tv", "apple tv+", "apple tv plus", "tv+"]),
  b("iheart.com", ["iheart", "iheartradio"]),
  b("deezer.com", ["deezer"]),
  b("qobuz.com", ["qobuz"]),
  b("amazonmusic.com", ["amazon music", "amazon unlimited music"]),
];
