import { b } from "./shared";

export const TRAVEL_RIDE_BRANDS = [
  b("uber.com", [
    "uber trip",
    "uber ride",
    "uber one",
    "uber monthly",
    "uber",
  ]),
  b("lyft.com", ["lyft", "lyft pink", "lyft plus"]),
  b("united.com", ["united airlines", "united air lines", "united mileage", "united club", "united.com", "united "]),
  b("delta.com", ["delta air lines", "delta airlines", "delta skymiles", "delta.com", "delta "]),
  b("aa.com", ["american airlines", "american air", "aa.com", "aa airlines"]),
  b("southwest.com", ["southwest airlines", "southwest air", "southwest"]),
  b("jetblue.com", ["jetblue", "jet blue"]),
  b("spirit.com", ["spirit airlines", "spirit air"]),
  b("flyfrontier.com", ["frontier airlines", "frontier air"]),
  b("alaskaair.com", ["alaska airlines", "alaska air"]),
  b("hawaiianairlines.com", ["hawaiian airlines", "hawaiian air"]),
  b("airbnb.com", ["airbnb", "air bnb", "air b and b"]),
  b("booking.com", ["booking.com", "booking holdings", "booking com"]),
  b("expedia.com", ["expedia", "expedia group"]),
  b("hotels.com", ["hotels.com", "hotels com"]),
  b("kayak.com", ["kayak"]),
  b("priceline.com", ["priceline"]),
  b("orbitz.com", ["orbitz"]),
  b("marriott.com", ["marriott bonvoy", "marriott"]),
  b("hilton.com", ["hilton honors", "hilton"]),
  b("hyatt.com", ["world of hyatt", "hyatt"]),
  b("ihg.com", ["ihg hotels", "ihg rewards", "ihg"]),
  b("choicehotels.com", ["choice hotels", "choice privileges"]),
  b("tripadvisor.com", ["tripadvisor", "trip advisor"]),
  b("turo.com", ["turo"]),
  b("zipcar.com", ["zipcar", "zip car"]),
  b("avis.com", ["avis budget", "avis car"]),
  b("hertz.com", ["hertz gold", "hertz"]),
  b("enterprise.com", ["enterprise rent", "enterprise car", "enterprise holdings"]),
  b("nationalcar.com", ["national car", "national emerald"]),
  b("sixt.com", ["sixt rent", "sixt"]),
  b("trainline.com", ["trainline"]),
  b("amtrak.com", ["amtrak", "amtrak guest"]),
];
